### ISSUE TITLE
Todo (urgent)

### ISSUE THREAD

**Issue by wareya** [wareya/faucmix#7]
- [ ] Take samplerate and buffer size into account when making stream. Remove floating point and mono controls
- [ ] Fix memory leaks (#3)
- [ ] Make sure there is no STL data structure usage in any inner loops, only in commands
